// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkerTransfer.Transfer.Infrastructure.Persistence;

#nullable disable

namespace WorkerTransfer.Transfer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransferDbContext))]
    [Migration("20260826160841_Transfermarkt")]
    partial class Transfermarkt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkerTransfer.Outbox.OutboxZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeliveredAt");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("WorkerTransfer.Transfer.Infrastructure.Persistence.AnfrageZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("SubjectId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("uq_market_requests_subject_tenant");

                    b.ToTable("market_requests", (string)null);
                });

            modelBuilder.Entity("WorkerTransfer.Transfer.Infrastructure.Persistence.MarktZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("availability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Employed")
                        .HasColumnType("boolean")
                        .HasColumnName("employed");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("market_status", (string)null);
                });

            modelBuilder.Entity("WorkerTransfer.Transfer.Infrastructure.Persistence.VorgangsZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("OfferFeeCents")
                        .HasColumnType("bigint")
                        .HasColumnName("offer_fee_cents");

                    b.Property<string>("OfferNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("offer_note");

                    b.Property<string>("OfferStartOn")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("offer_start_on");

                    b.Property<bool>("ReleaseConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("release_confirmed");

                    b.Property<bool>("RequiresRelease")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_release");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("SubjectId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("uq_running_transfer")
                        .HasFilter("status IN ('interested', 'talking', 'offered', 'accepted')");

                    b.ToTable("transfers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
