// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkerTransfer.GitHub.Infrastructure.Persistence;

#nullable disable

namespace WorkerTransfer.GitHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GitHubDbContext))]
    partial class GitHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkerTransfer.GitHub.Infrastructure.Persistence.VerbindungsZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Challenge")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("challenge");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<bool>("LanguagesComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("languages_complete");

                    b.Property<string>("Login")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("login");

                    b.Property<string>("Repositories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("repositories");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.ToTable("github_connections", (string)null);

                    b.HasAnnotation("WorkerTransfer:Personenzeile", true);
                });
#pragma warning restore 612, 618
        }
    }
}
