<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WorkerTransfer.Profile.Application\WorkerTransfer.Profile.Application.csproj" />
    <ProjectReference Include="..\WorkerTransfer.Profile.Domain\WorkerTransfer.Profile.Domain.csproj" />
    <ProjectReference Include="..\..\shared\WorkerTransfer.Contracts.Consent\WorkerTransfer.Contracts.Consent.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Girder.Data.EntityFrameworkCore" />
    <PackageReference Include="Girder.Infrastructure" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
