// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkerTransfer.Profile.Domain.Pruefspur;
using WorkerTransfer.Profile.Infrastructure.Persistence;

#nullable disable

namespace WorkerTransfer.Profile.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pruef_handlung", new[] { "profil_angelegt", "profil_geaendert", "profil_geloescht" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pruef_handlung", "pruefhandlung", new[] { "profil_angelegt", "profil_geaendert", "profil_geloescht" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkerTransfer.Profile.Infrastructure.Persistence.ProfilZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AngelegtAm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Faehigkeiten")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<DateTimeOffset>("GeaendertAm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<bool>("RemoteMoeglich")
                        .HasColumnType("boolean")
                        .HasColumnName("remote_ok");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Ueberschrift")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.HasKey("Id");

                    b.HasIndex("GeaendertAm", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_profiles_seite");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("WorkerTransfer.Profile.Infrastructure.Persistence.Pruefzeile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AkteurId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("BetroffenId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("Daten")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("FirmaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("GeschehenAm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Pruefhandlung>("Handlung")
                        .HasColumnType("pruef_handlung")
                        .HasColumnName("action");

                    b.Property<string>("Korrelation")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.HasKey("Id");

                    b.ToTable("audit_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
