<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\scout-service\WorkerTransfer.Scout.Api\WorkerTransfer.Scout.Api.csproj" />
    <ProjectReference Include="..\..\src\scout-service\WorkerTransfer.Scout.Application\WorkerTransfer.Scout.Application.csproj" />
    <ProjectReference Include="..\..\src\scout-service\WorkerTransfer.Scout.Contracts\WorkerTransfer.Scout.Contracts.csproj" />
    <ProjectReference Include="..\..\src\scout-service\WorkerTransfer.Scout.Domain\WorkerTransfer.Scout.Domain.csproj" />
    <ProjectReference Include="..\..\src\scout-service\WorkerTransfer.Scout.Infrastructure\WorkerTransfer.Scout.Infrastructure.csproj" />
  </ItemGroup>

</Project>
