<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\applications-service\WorkerTransfer.Applications.Api\WorkerTransfer.Applications.Api.csproj" />
    <ProjectReference Include="..\..\src\applications-service\WorkerTransfer.Applications.Application\WorkerTransfer.Applications.Application.csproj" />
    <ProjectReference Include="..\..\src\applications-service\WorkerTransfer.Applications.Domain\WorkerTransfer.Applications.Domain.csproj" />
    <ProjectReference Include="..\..\src\applications-service\WorkerTransfer.Applications.Infrastructure\WorkerTransfer.Applications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\shared\WorkerTransfer.Contracts.Identity\WorkerTransfer.Contracts.Identity.csproj" />
  </ItemGroup>
</Project>
