<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WorkerTransfer.Jobs.Domain\WorkerTransfer.Jobs.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Girder.Abstractions" />
    <PackageReference Include="Girder.Application" />
  </ItemGroup>
</Project>
